### ISSUE TITLE
Rails 6 Support?

### ISSUE THREAD

**Issue by hmontazeri** [render-examples/rails#12]
Hi any plans to support Rails 6 on render? 

The reason why I'm asking: Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/pids/server.pid

https://www.alanvardy.com/post/puma-server-not-loading

**Comment by wendorf** [comment]
Hi @hmontazeri , we have created a new https://github.com/render-examples/rails-6 repository with Rails 6 support, and https://render.com/docs/deploy-rails has been updated to use this new repository.
